# Generated by Django 3.1.7 on 2021-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210429_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(default='blog_pics/default.jpg', upload_to='blog_pics/% Y/% m/% d/'),
        ),
    ]
