# Generated by Django 3.1.7 on 2021-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_blog_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(default='blog_pics/default.jpg', upload_to='blog_pics/'),
        ),
    ]
